### ISSUE TITLE
Issue with ensureMiddleWareIsLast after Meteor update to 1.6.1

### ISSUE THREAD

**Issue by arminschleicher** [abecks/meteor-inject-data#4]
```
20180205-07:40:28.061(1)? (STDERR) error on fast-rendering path: /userdata/event-invoices/2017/11 ; error: TypeError: Cannot read property 'name' of undefined
W20180205-07:40:28.062(1)? (STDERR)     at ensureMiddlewareIsLast (packages/staringatlights_inject-data.js:104:29)
W20180205-07:40:28.062(1)? (STDERR)     at Object.pushData (packages/staringatlights_inject-data.js:134:5)
W20180205-07:40:28.062(1)? (STDERR)     at packages/staringatlights_fast-render.js:214:18
W20180205-07:40:28.063(1)? (STDERR)     at packages/staringatlights_fast-render.js:288:7
```

I get the following error on every route after updating to Meteor 1.6.1. After forking the package and investigating the ensureMiddleWareIsLast function, it seems like the injectDataMiddleware handle is not present. What can be the issue here? Thanks!

**Comment by abecks** [comment]
See #5
